Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Models/Contacts/AddViewContactViewModel.cs
using PhoneBook.Core.Entities.Phones;
using PhoneBook.Core.Entities.Tags;
using System.ComponentModel.DataAnnotations;

namespace PhoneBook.Endpoints.UI.MVC.Models.Contacts;

public abstract class AddNewContactViewModel
{
    [Required]
    [StringLength(100, MinimumLength = 2)]
    public string FirstName { get; set; } = "";

    [Required]
    [StringLength(200, MinimumLength = 2)]
    public string LastName { get; set; } = "";

    [Required]
    [EmailAddress]
    [StringLength(100, MinimumLength = 3)]
    public string Email { get; set; } = "";

    [StringLength(500)]
    public string? Address { get; set; }

    public IFormFile Image { get; set; }

    [StringLength(15)]
    public string PhoneNumber { get; set; } = "";
}
public class AddNewContactDisplayViewModel : AddNewContactViewModel
{
    public List<Tag> TagsForDisplay { get; set; } = new List<Tag>();
    public List<PhoneType> PhoneTypesForDisplay { get; set; } = new List<PhoneType>();
}
public class AddNewContactGetViewModel : AddNewContactViewModel
{
    public List<int> SelectedTag { get; set; } = new List<int>();
    public List<int> SelectedPhoneType { get; set; } = new List<int>();
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Models/Contacts/ContactDetailsViewModel.cs
using PhoneBook.Core.Entities.Phones;
using PhoneBook.Core.Entities.Tags;

namespace PhoneBook.Endpoints.UI.MVC.Models.Contacts;

public class ContactDetailsViewModel: ContactViewModel
{
    public int ContactId { get; set; }
    public List<Phone> Phones { get; set; } = new List<Phone>();
    public List<Tag> Tags { get; set; } = new List<Tag>();
    public List<PhoneType> PhoneTypes { get; set; } = new List<PhoneType>();

    //public string FirstName { get; set; }
    //public string LastName { get; set; }
    //public string Email { get; set; }
    //public string? Address { get; set; }
    //public string Image { get; set; }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Models/Contacts/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PhoneBook.Endpoints.UI.MVC.Models.Contacts
{
    public class ContactViewModel
    {
        public int Id { get; set; }
        //[Display(Name = "نام")]
        //[Required(ErrorMessage = "وارد کردن {0} الزامی است")]
        //[StringLength(50, MinimumLength = 2)]
        public string FirstName { get; set; }

        //[Display(Name = "نام خانوادگی")]
        //[Required(ErrorMessage = "وارد کردن {0} الزامی است")]
        //[StringLength(50, MinimumLength = 2)]
        public string LastName { get; set; }

        //[Display(Name = "ایمیل")]
        //[Required(ErrorMessage = "وارد کردن {0} الزامی است")]
        //[EmailAddress]
        public string Email { get; set; }

        //[Display(Name = "آدرس")]
        //[StringLength(500)]
        public string Address { get; set; }

        public string Image { get; set; }

    }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Models/Contacts/EditViewContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PhoneBook.Endpoints.UI.MVC.Models.Contacts;

public class EditViewContactViewModel
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    //[Required(AllowEmptyStrings = true)]
    public string CurrentImage { get; set; }

    public IFormFile? Image { get; set; }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Core.Contracts.Contacts;
using PhoneBook.Core.Contracts.Phones;
using PhoneBook.Core.Contracts.Tags;
using PhoneBook.Core.Entities.Contacts;
using PhoneBook.Core.Entities.Phones;
using PhoneBook.Endpoints.UI.MVC.Models.Contacts;

namespace PhoneBook.Endpoints.UI.MVC.Controllers;

[Authorize]
public class ContactController : Controller
{
    private readonly IContactService contactService;
    private readonly ITagService tagService;
    private readonly IPhoneTypeService phoneTypeService;

    public ContactController(IContactService contactService, ITagService tagService, IPhoneTypeService phoneTypeService)
    {
        this.contactService = contactService;
        this.tagService = tagService;
        this.phoneTypeService = phoneTypeService;
    }

    public IActionResult Index()
    {
        ViewBag.PageTitle = "List of Contacts";

        var contacts = contactService.GetAll().ToList();
        return View(contacts);
    }

    public IActionResult Add()
    {
        ViewBag.PageTitle = "Add Contact";

        AddNewContactDisplayViewModel model = new()
        {
            TagsForDisplay = tagService.GetAll().ToList(),
            PhoneTypesForDisplay = phoneTypeService.GetAll().ToList()
        };
        return View(model);
    }

    [HttpPost]
    public IActionResult Add(AddNewContactGetViewModel model)
    {
        if (ModelState.IsValid)
        {
            Contact contact = new Contact
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Address = model.Address,
                Email = model.Email,
                Phones = new List<Phone>(model.SelectedPhoneType.Select(c => new Phone
                {
                    PhoneNumber = model.PhoneNumber,
                    PhoneTypeId = c
                }).ToList()),
                Tags = new List<ContactTag>(model.SelectedTag.Select(c => new ContactTag
                {
                    TagId = c
                }).ToList())
            };

            if (model.Image.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    model.Image.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    contact.Image = Convert.ToBase64String(fileBytes);
                }
            }
            var result = contactService.Add(contact);
            if (result != null)
            {
                return RedirectToAction("Index");
            }
        }

        ViewBag.SelectedItem = model?.SelectedTag;

        ViewBag.SeletecdPhoneTypeItem = model?.SelectedPhoneType;

        AddNewContactDisplayViewModel modelForDisplay = new()
        {
            FirstName = model.FirstName,
            LastName = model.LastName,
            Email = model.Email,
            Address = model.Address,
            Image = model.Image
        };

        modelForDisplay.TagsForDisplay = tagService.GetAll().ToList();

        return View(modelForDisplay);
    }

    public IActionResult Detail(int id)
    {
        ViewBag.PageTitle = "Details of Contact";

        var contact = contactService.GetContactWithChilds(id);
        if (contact != null)
        {
            var model = new ContactDetailsViewModel
            {
                ContactId = contact.Id,
                FirstName = contact.FirstName,
                LastName = contact.LastName,
                Email = contact.Email,
                Address = contact.Address,
                Image = contact.Image,
                Phones = contact.Phones
            };
            model.Tags = tagService.GetContactTagsByContactId(contact.Id);
            model.PhoneTypes = phoneTypeService.GetContactPhoneTypesByContactId(contact.Id);

            return View(model);
        }
        return View();
    }

    public IActionResult Update(int id)
    {
        ViewBag.PageTitle = "Edit Contact";

        var contact = contactService.FindById(id);

        EditViewContactViewModel model = new()
        {
            Id = contact.Id,
            FirstName = contact.FirstName,
            LastName = contact.LastName,
            Email = contact.Email,
            Address = contact.Address,
            CurrentImage = contact.Image
            //Image = String.Format("data:image/gif;base64,{0}", contact.Image)
        };

        //byte[] bytes = Convert.FromBase64String(contact.Image);
        //MemoryStream stream = new MemoryStream(bytes);
        //////model.Image = new FormFile(stream, 0, bytes.Length, contact.Image, contact.Image);
        //model.Image = new FormFile(stream, 0, stream.Length,"","");


        return View(model);
    }

    [HttpPost]
    public IActionResult Update(EditViewContactViewModel model)
    {
        var contact = contactService.FindById(model.Id);

        ModelState.Remove("CurrentImage"); // to omit CurrentImage Validation Error

        if (ModelState.IsValid)
        {
            contact.FirstName = model.FirstName;
            contact.LastName = model.LastName;
            contact.Address = model.Address;
            contact.Email = model.Email;
            if (model.Image != null)
            {
                if (model.Image.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        model.Image.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        contact.Image = Convert.ToBase64String(fileBytes);
                    }
                }
            }

            contactService.Update(contact);

            return RedirectToAction("Index");
        }

        return View(model);
    }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Controllers/PhoneController.cs
using Microsoft.AspNetCore.Mvc;

namespace PhoneBook.Endpoints.UI.MVC.Controllers
{
    public class PhoneController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;

namespace PhoneBook.Endpoints.UI.MVC.Controllers
{
    public class TagController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Contact/Add.cshtml
@model PhoneBook.Endpoints.UI.MVC.Models.Contacts.AddNewContactDisplayViewModel

@{
    List<int> selectedTag = (List<int>)ViewBag.SelectedItem;
    List<int> selectedPhoneType = (List<int>)ViewBag.SeletecdPhoneTypeItem;
}

@section head
{
<link href="~/vendor/select2/dist/css/select2.min.css" rel="stylesheet" />
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Contact Information</h6>
    </div>
    <div class="card-body">

        <form asp-controller="Contact" asp-action="Add" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>

            <div class="form-group">
                <label asp-for="FirstName">First Name</label>
                <input type="text" asp-for="FirstName" class="form-control" maxlength="100" />
                <span asp-validation-for="FirstName"></span>
            </div>

            <div class="form-group">
                <label asp-for="LastName">Last Name</label>
                <input type="text" asp-for="LastName" class="form-control" maxlength="200" />
                <span asp-validation-for="LastName"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="email" asp-for="Email" class="form-control" maxlength="100" />
                <span asp-validation-for="Email"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhoneNumber">PhoneNumber</label>
                <input type="text" asp-for="PhoneNumber" class="form-control" maxlength="15" />
                <span asp-validation-for="PhoneNumber"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhoneTypesForDisplay">Phone Type</label>
                <select class="form-control select2" name="SelectedPhoneType">
                    @foreach (var item in Model.PhoneTypesForDisplay)
                    {
                        if (ViewBag.SelectedPhoneType != null && selectedPhoneType.Contains(item.Id))
                        {
                            <option selected value="@item.Id">@item.Name</option>
                        }
                        else
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    }
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Address">Address</label>
                <input type="text" asp-for="Address" class="form-control" maxlength="500" />
                <span asp-validation-for="Address"></span>
            </div>

            <div class="form-group">
                <label asp-for="Image">Image</label>
                <input type="file" asp-for="Image" class="form-control" />
                <span asp-validation-for="Image"></span>
            </div>

            <div class="form-group">
                <label asp-for="TagsForDisplay">Tag</label>
                <select class="form-control select2" name="SelectedTag" multiple>
                    @foreach (var item in Model.TagsForDisplay)
                    {
                        if (ViewBag.SelectedItem != null && selectedTag.Contains(item.Id))
                        {
                            <option selected value="@item.Id">@item.Name</option>
                        }
                        else
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    }
                </select>
            </div>

            @*<div class="form-group">*@
            @*<button type="button" class="btn btn-secondary" asp-controller="People" asp-action="Index">Cancel</button>*@
            <input type="button" class="btn btn-secondary" value="Cancel" onclick="@("window.location.href='" + @Url.Action("Index", "Contact") + "'");" />
            <input type="submit" class="btn btn-success" value="Save" />
            @*</div>*@

        </form>

    </div>
</div>


@section scripts
{
<script src="~/vendor/select2/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.select2').select2();

        $(".collapse-item").click(function() {
            $(this).addClass("active");
        });

        if (!$("#collapseContacts").hasClass("show")) {
            $("#collapseContacts").addClass("show");   
        }

    });
</script>
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Contact/Detail.cshtml
@model PhoneBook.Endpoints.UI.MVC.Models.Contacts.ContactDetailsViewModel

@{
    var imgSrc = String.Format("data:image/gif;base64,{0}", Model.Image);
    var fullName = Model.FirstName + " " + Model.LastName;
}

@*Image and Information*@
@*<div class="d-flex bd-highlight border flex-wrap">
    <div class="p-2 bd-highlight ">
    <img src="@imgSrc" height="150" width="150" class="img-thumbnail rounded-circle" alt="@fullName" />
    </div>
    <div class="p-2 bd-highlight flex-grow-1">
    <div>
    <b><label asp-for="FirstName"></label> : </b> @Model.FirstName
    </div>
    <div>
    <b><label asp-for="LastName"></label> : </b> @Model.LastName
    </div>
    <div>
    <b><label asp-for="Email"></label> : </b> @Model.Email
    </div>
    <div>
    <b><label asp-for="Address"></label> : </b> @Model.Address
    </div>
    </div>
    <div class="p-2 bd-highlight">
    <div>
    <a class="btn-sm btn-outline-primary" asp-controller="Contact" asp-action="Update" asp-route-id="@Model.ContactId"><i class="fa fa-edit"></i></a>
    <a class="btn-sm btn-outline-danger" asp-controller="Contact" asp-action="Delete" asp-route-id="@Model.ContactId"><i class="fa fa-trash"></i></a>
    </div>
    </div>
    </div>*@


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">General Information</h6>
    </div>
    <div class="card-body">

        @*Image and Information*@
        <div class="d-flex bd-highlight flex-wrap">
            <div class="bd-highlight ">
                <img src="@imgSrc" height="150" width="150" class="img-thumbnail rounded-circle" alt="@fullName" />
            </div>
            <div class="p-2 bd-highlight flex-grow-1">
                <div>
                    <b><label asp-for="FirstName"></label> : </b> @Model.FirstName
                </div>
                <div>
                    <b><label asp-for="LastName"></label> : </b> @Model.LastName
                </div>
                <div>
                    <b><label asp-for="Email"></label> : </b> @Model.Email
                </div>
                <div>
                    <b><label asp-for="Address"></label> : </b> @Model.Address
                </div>
            </div>
            <div class="bd-highlight">
                <div>
                    <a class="btn-sm btn-outline-primary" asp-controller="Contact" asp-action="Update" asp-route-id="@Model.ContactId"><i class="fa fa-edit"></i></a>
                    <a class="btn-sm btn-outline-danger" asp-controller="Contact" asp-action="Delete" asp-route-id="@Model.ContactId"><i class="fa fa-trash"></i></a>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tags</h6>
    </div>
    <div class="card-body">

        @*Tags*@
        <div class="d-flex bd-highlight flex-wrap justify-content-around">
            <div class="bd-highlight flex-grow-1 ">
                <div>
                    @*<b>Tags : </b>*@
                    @foreach (var item in Model.Tags)
                    {
                        <div class="d-flex">
                            <div class="mr-auto p-2">
                                @*<div>@item.Name</div>*@
                                <span class="badge badge-primary">@item.Name</span>
                            </div>
                            <div class="ml-auto p-2">
                                <a class="btn-sm btn-outline-primary" asp-controller="Tag" asp-action="Update" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                                <a class="btn-sm btn-outline-danger" asp-controller="Tag" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash"></i></a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Phones</h6>
    </div>
    <div class="card-body">

        @*Phones*@
        <div class="d-flex bd-highlight flex-wrap justify-content-around">
            <div class="bd-highlight flex-grow-1 ">
                <div>
                    @foreach (var item in Model.Phones)
                    {
                        <div class="d-flex">
                            <div class="mr-auto p-2">
                                <div>
                                    <span class="badge badge-dark">@item.PhoneType.Name</span>  @item.PhoneNumber
                                </div>
                            </div>
                            <div class="ml-auto p-2">
                                <a class="btn-sm btn-outline-primary" asp-controller="Phone" asp-action="Update" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                                <a class="btn-sm btn-outline-danger" asp-controller="Phone" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash"></i></a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

    </div>
</div>

@section scripts
{
<script src="~/vendor/select2/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {

        $(".collapse-item").click(function() {
            $(this).addClass("active");
        });

        if (!$("#collapseContacts").hasClass("show")) {
            $("#collapseContacts").addClass("show");
        }
    });
</script>
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Contact/Index.cshtml
@model List<PhoneBook.Core.Entities.Contacts.Contact>

@if (Model != null && Model.Count > 0)
{
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List of Contacts</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="align-middle text-center">Photo</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th class="align-middle text-center">Actions</th>
                        </tr>
                    </thead>
                    @*<tfoot>
                        <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Age</th>
                        <th>Start date</th>
                        <th>Salary</th>
                        </tr>
                        </tfoot>
                    *@
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                @{
                                    var imgSrc = String.Format("data:image/gif;base64,{0}", item.Image);
                                    var fullName = item.FirstName + " " + item.LastName;
                                }
                                <td class="align-middle text-center">
                                    <img src="@imgSrc" height="75" width="75" class="img-thumbnail rounded-circle" alt="@fullName" />
                                </td>
                                <td class="align-middle">@item.FirstName</td>
                                <td class="align-middle">@item.LastName</td>
                                <td class="align-middle">@item.Email</td>
                                <td class="align-middle">@item.Address</td>
                                <td class="align-middle text-center">
                                    @*  <a asp-controller="Contact" asp-action="Detail" asp-route-id="@item.Id" class="badge badge-group-sm badge-primary">Detail</a>
                                        <a asp-controller="Contact" asp-action="Update" asp-route-id="@item.Id" class="badge badge-group-sm badge-warning">Edit</a>
                                        <a asp-controller="Contact" asp-action="Delete" asp-route-id="@item.Id" class="badge badge-group-sm badge-danger">Delete</a>
                                    *@
                                    <a class="btn-sm btn-outline-secondary" asp-controller="Contact" asp-action="Detail" asp-route-id="@item.Id"><i class="far fa-address-card"></i></a>
                                    <a class="btn-sm btn-outline-primary" asp-controller="Contact" asp-action="Update" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                                    <a class="btn-sm btn-outline-danger" asp-controller="Contact" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>

}
else
{
    @*<div class="alert alert-info" role="alert">
        There is no any recored in DB.
        </div>*@

    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>Notice!</strong> There is no any recored in DB.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}


@section scripts
{
<script>
    $(document).ready(function () {

        $(".collapse-item").click(function() {
            $(this).addClass("active");
        });
        
        if (!$("#collapseContacts").hasClass("show")) {
            $("#collapseContacts").addClass("show");   
        }

    });
</script>
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Contact/Update.cshtml
@model PhoneBook.Endpoints.UI.MVC.Models.Contacts.EditViewContactViewModel

@{
    var imgSrc = String.Format("data:image/gif;base64,{0}", Model.CurrentImage);
    var fullName = Model.FirstName + " " + Model.LastName;
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Contact Information</h6>
    </div>
    <div class="card-body">

        <form asp-controller="Contact" asp-action="Update" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>

            <div class="form-group">
                <div asp-for="Image">
                    <img id="blah" src="@imgSrc" height="150" width="150" class="img-thumbnail rounded-circle" alt="@fullName" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Image"></label>
                <input id="imgInp" type="file" accept="image/*" asp-for="Image" name="Image" class="form-control" />
                <span asp-validation-for="Image"></span>
            </div>

            <div class="form-group">
                <label asp-for="FirstName">First Name</label>
                <input type="text" asp-for="FirstName" class="form-control" maxlength="100" />
                <span asp-validation-for="FirstName"></span>
            </div>

            <div class="form-group">
                <label asp-for="LastName">Last Name</label>
                <input type="text" asp-for="LastName" class="form-control" maxlength="200" />
                <span asp-validation-for="LastName"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="email" asp-for="Email" class="form-control" maxlength="100" />
                <span asp-validation-for="Email"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address">Address</label>
                <input type="text" asp-for="Address" class="form-control" maxlength="500" />
                <span asp-validation-for="Address"></span>
            </div>




            <input type="button" class="btn btn-secondary" value="Cancel" onclick="@("window.location.href='" + @Url.Action("Index", "Contact") + "'");" />
            <input type="submit" class="btn btn-success" value="Save" />

        </form>

    </div>
</div>


@section scripts
{
<script src="~/vendor/select2/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.select2').select2();

        $(".collapse-item").click(function() {
            $(this).addClass("active");
        });

        if (!$("#collapseContacts").hasClass("show")) {
            $("#collapseContacts").addClass("show");   
        }

        imgInp.onchange = evt => {
            const [file] = imgInp.files
            if (file) {
                blah.src = URL.createObjectURL(file)
            }
        }
    });
</script>
}