Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Core.Contracts.Contacts;
using PhoneBook.Core.Contracts.Phones;
using PhoneBook.Core.Contracts.Tags;
using PhoneBook.Core.Entities.Contacts;
using PhoneBook.Core.Entities.Phones;
using PhoneBook.Endpoints.UI.MVC.Models.Contacts;

namespace PhoneBook.Endpoints.UI.MVC.Controllers;

[Authorize]
public class ContactController : Controller
{
    private readonly IContactService contactService;
    private readonly ITagService tagService;
    private readonly IPhoneTypeService phoneTypeService;

    public ContactController(IContactService contactService, ITagService tagService, IPhoneTypeService phoneTypeService)
    {
        this.contactService = contactService;
        this.tagService = tagService;
        this.phoneTypeService = phoneTypeService;
    }

    public IActionResult Index()
    {
        ViewBag.PageTitle = "List of Contacts";

        var contacts = contactService.GetAll().ToList();
        return View(contacts);
    }

    public IActionResult Add()
    {
        ViewBag.PageTitle = "Add Contact";

        AddNewContactDisplayViewModel model = new()
        {
            TagsForDisplay = tagService.GetAll().ToList(),
            PhoneTypesForDisplay = phoneTypeService.GetAll().ToList()
        };
        return View(model);
    }

    [HttpPost]
    public IActionResult Add(AddNewContactGetViewModel model)
    {
        if (ModelState.IsValid)
        {
            Contact contact = new Contact
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Address = model.Address,
                Email = model.Email,
                Phones = new List<Phone>(model.SelectedPhoneType.Select(c => new Phone
                {
                    PhoneNumber = model.PhoneNumber,
                    PhoneTypeId = c
                }).ToList()),
                Tags = new List<ContactTag>(model.SelectedTag.Select(c => new ContactTag
                {
                    TagId = c
                }).ToList())
            };

            if (model.Image.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    model.Image.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    contact.Image = Convert.ToBase64String(fileBytes);
                }
            }
            var result = contactService.Add(contact);
            if (result != null)
            {
                return RedirectToAction("Index");
            }
        }

        ViewBag.SelectedItem = model?.SelectedTag;

        ViewBag.SeletecdPhoneTypeItem = model?.SelectedPhoneType;

        AddNewContactDisplayViewModel modelForDisplay = new()
        {
            FirstName = model.FirstName,
            LastName = model.LastName,
            Email = model.Email,
            Address = model.Address,
            Image = model.Image
        };

        modelForDisplay.TagsForDisplay = tagService.GetAll().ToList();

        return View(modelForDisplay);
    }

    public IActionResult Detail(int id)
    {
        ViewBag.PageTitle = "Details of Contact";

        var contact = contactService.GetContactWithChilds(id);
        if (contact != null)
        {
            var model = new ContactDetailsViewModel
            {
                ContactId = contact.Id,
                FirstName = contact.FirstName,
                LastName = contact.LastName,
                Email = contact.Email,
                Address = contact.Address,
                Image = contact.Image,
                Phones = contact.Phones
            };
            model.Tags = tagService.GetContactTagsByContactId(contact.Id);
            model.PhoneTypes = phoneTypeService.GetContactPhoneTypesByContactId(contact.Id);

            return View(model);
        }
        return View();
    }

    public IActionResult Update(int id)
    {
        ViewBag.PageTitle = "Edit Contact";

        var contact = contactService.FindById(id);

        EditViewContactViewModel model = new()
        {
            Id = contact.Id,
            FirstName = contact.FirstName,
            LastName = contact.LastName,
            Email = contact.Email,
            Address = contact.Address,
            CurrentImage = contact.Image
            //Image = String.Format("data:image/gif;base64,{0}", contact.Image)
        };

        //byte[] bytes = Convert.FromBase64String(contact.Image);
        //MemoryStream stream = new MemoryStream(bytes);
        //////model.Image = new FormFile(stream, 0, bytes.Length, contact.Image, contact.Image);
        //model.Image = new FormFile(stream, 0, stream.Length,"","");


        return View(model);
    }

    [HttpPost]
    public IActionResult Update(EditViewContactViewModel model)
    {
        var contact = contactService.FindById(model.Id);

        ModelState.Remove("CurrentImage"); // to omit CurrentImage Validation Error

        if (ModelState.IsValid)
        {
            contact.FirstName = model.FirstName;
            contact.LastName = model.LastName;
            contact.Address = model.Address;
            contact.Email = model.Email;
            if (model.Image != null)
            {
                if (model.Image.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        model.Image.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        contact.Image = Convert.ToBase64String(fileBytes);
                    }
                }
            }

            contactService.Update(contact);

            return RedirectToAction("Index");
        }

        return View(model);
    }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PhoneBook.Endpoints.UI.MVC.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            ViewBag.PageTitle = "List of Roles";

            var roles = roleManager.Roles.ToList();
            return View(roles);
        }


        public IActionResult Add()
        {
            ViewBag.PageTitle = "Create a Role";


            return View();
        }

        [HttpPost]
        public IActionResult Add(IdentityRole identityRole)
        {
            IdentityRole role = new IdentityRole
            {
                Name = identityRole.Name
            };
            var result = roleManager.CreateAsync(role).Result;
            return RedirectToAction("Index");
        }

        public IActionResult Update(string id)
        {
            var role = roleManager.FindByIdAsync(id).Result;

            IdentityRole identityRole = new IdentityRole
            {
                Name = role.Name,
            };

            return View(identityRole);
        }

        [HttpPost]
        public IActionResult Update(IdentityRole model)
        {
            var role = roleManager.FindByIdAsync(model.Id).Result;

            role.Name = model.Name;

            var result = roleManager.UpdateAsync(role).Result;

            return RedirectToAction("Index");
        }


        public IActionResult Delete(string id)
        {
            var user = roleManager.FindByIdAsync(id).Result;

            if (user != null)
            {
                var result = roleManager.DeleteAsync(user).Result;

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }

            return View();
        }

        
    }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PhoneBook.Endpoints.UI.MVC.Models.AAA;

namespace PhoneBook.Endpoints.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<AppUser> userManager,
                              RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            ViewBag.PageTitle = "List of Users";

            var users = userManager.Users.ToList();
            return View(users);
        }

        public IActionResult Add()
        {
            ViewBag.PageTitle = "Add User";


            AddNewUserDisplayViewModel model = new AddNewUserDisplayViewModel
            {
                RolesForDisplay = roleManager.Roles.Select(c=> new IdentityRole
                {
                    Id = c.Id,
                    Name = c.Name,
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddNewUserGetViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = new AppUser
                {
                    UserName = model.Username,
                    Email = model.Email,
                };

                var result = userManager.CreateAsync(user, model.Password).Result;

                if (result.Succeeded)
                {
                    var roles = new List<string>(model.SelectedRoles.ToList());

                    foreach (var item in roles)
                    {
                        var selectedRoleName = roleManager.FindByIdAsync(item).Result;
                        var resultRole = userManager.AddToRoleAsync(user, selectedRoleName.Name).Result;
                    }

                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }

            return View(model);
        }

        public IActionResult Detail(string id)
        {
            ViewBag.PageTitle = "User Details";

            var user = userManager.FindByIdAsync(id).Result;

            DetailUserViewModel model = new DetailUserViewModel
            {
                Id = id,
                Email = user.Email,
                Username = user.UserName,
            };

            //Choose only related role of the user not all of roles stored in DB
            model.RolesForDisplay = roleManager.Roles.ToList();            

            return View(model);
        }

        public IActionResult Update(string id)
        {
            ViewBag.PageTitle = "Update User";

            var user = userManager.FindByIdAsync(id).Result;

            UpdateUserViewModel model = new UpdateUserViewModel
            {
                Id = id,
                Email = user.Email,
                Username = user.UserName,
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(string id, UpdateUserViewModel model)
        {
            var user = userManager.FindByIdAsync(id).Result;

            if (user != null)
            {
                user.Email = model.Email;
                user.UserName = model.Username;

                var result = userManager.UpdateAsync(user).Result;

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }
            return View(model);
        }

        public IActionResult Delete(string id)
        {
            var user = userManager.FindByIdAsync(id).Result;

            if (user != null)
            {
                var result = userManager.DeleteAsync(user).Result;

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }

            return View();
        }

        public IActionResult AddToRole(string id, string roleName)
        {
            var user = userManager.FindByIdAsync(id).Result;

            if (user != null)
            {
                var result = userManager.AddToRoleAsync(user, roleName).Result;
            }

            return RedirectToAction("Index");
        }
    }
}

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Shared/_ContentWrapper.cshtml
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                           aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                         aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small"
                                       placeholder="Search for..." aria-label="Search"
                                       aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>

                <!-- Nav Item - Alerts -->
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-bell fa-fw"></i>
                        <!-- Counter - Alerts -->
                        <span class="badge badge-danger badge-counter">3+</span>
                    </a>
                    <!-- Dropdown - Alerts -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="alertsDropdown">
                        <h6 class="dropdown-header">
                            Alerts Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-primary">
                                    <i class="fas fa-file-alt text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 12, 2019</div>
                                <span class="font-weight-bold">A new monthly report is ready to download!</span>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-success">
                                    <i class="fas fa-donate text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 7, 2019</div>
                                $290.29 has been deposited into your account!
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-warning">
                                    <i class="fas fa-exclamation-triangle text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 2, 2019</div>
                                Spending Alert: We've noticed unusually high spending for your account.
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                    </div>
                </li>

                <!-- Nav Item - Messages -->
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-envelope fa-fw"></i>
                        <!-- Counter - Messages -->
                        <span class="badge badge-danger badge-counter">7</span>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="messagesDropdown">
                        <h6 class="dropdown-header">
                            Message Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="~/img/undraw_profile_1.svg"
                                     alt="...">
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div class="font-weight-bold">
                                <div class="text-truncate">
                                    Hi there! I am wondering if you can help me with a
                                    problem I've been having.
                                </div>
                                <div class="small text-gray-500">Emily Fowler · 58m</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="~/img/undraw_profile_2.svg"
                                     alt="...">
                                <div class="status-indicator"></div>
                            </div>
                            <div>
                                <div class="text-truncate">
                                    I have the photos that you ordered last month, how
                                    would you like them sent to you?
                                </div>
                                <div class="small text-gray-500">Jae Chun · 1d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="~/img/undraw_profile_3.svg"
                                     alt="...">
                                <div class="status-indicator bg-warning"></div>
                            </div>
                            <div>
                                <div class="text-truncate">
                                    Last month's report looks great, I am very happy with
                                    the progress so far, keep up the good work!
                                </div>
                                <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src="~/img~/img/dropdown.jpg"
                                     alt="...">
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div>
                                <div class="text-truncate">
                                    Am I a good boy? The reason I ask is because someone
                                    told me that people say this to all dogs, even if they aren't good...
                                </div>
                                <div class="small text-gray-500">Chicken the Dog · 2w</div>
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                    </div>
                </li>

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                        <img class="img-profile rounded-circle"
                             src="~/img/undraw_profile.svg">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Your Website 2020</span>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->

</div>

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Shared/_Footer.cshtml
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Shared/_LogoutModal.cshtml
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Shared/_ScrollToTop.cshtml
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

Sources/04. Endpoints/PhoneBook.Endpoints.UI.MVC/Views/Shared/_Sidebar.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
        @*<div class="sidebar-brand-icon rotate-n-15">*@
        <div class="sidebar-brand-icon">
            @*<i class="fas fa-laugh-wink"></i>*@
            <i class="fas fa-address-book"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Phone Book</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" asp-controller="Home" asp-action="Index">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Contacts Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseContacts"
           aria-expanded="true" aria-controls="collapseContacts">
            <i class="fa fa-address-book"></i>
            <span>Contacts</span>
        </a>
        <div id="collapseContacts" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Contacts Components:</h6>
                @*<a class="collapse-item" href="buttons.html">Add</a>
                <a class="collapse-item active" href="cards.html">List</a>*@
                <a class="collapse-item" asp-controller="Contact" asp-action="Add">Add</a>
                <a class="collapse-item" asp-controller="Contact" asp-action="Index">List</a>
            </div>
        </div>
    </li>


    <!-- Nav Item - Users Management Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUsers"
           aria-expanded="true" aria-controls="collapseUsers">
            <i class="fas fa-users"></i>
            <span>Users</span>
        </a>
        <div id="collapseUsers" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Users Components:</h6>
                <a class="collapse-item" asp-controller="User" asp-action="Add">Add</a>
@*                <a class="collapse-item" asp-controller="User" asp-action="Update">Update</a>
                <a class="collapse-item" asp-controller="User" asp-action="Delete">Delete</a>
*@                <a class="collapse-item" asp-controller="User" asp-action="Index">List</a>
            </div>
        </div>
    </li>


        <!-- Nav Item - Roles Management Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseRoles"
           aria-expanded="true" aria-controls="collapseRoles">
            <i class="fas fa-shield-alt"></i>
            <span>Roles</span>
        </a>
        <div id="collapseRoles" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Users Components:</h6>
                <a class="collapse-item" asp-controller="Role" asp-action="Add">Add</a>
@*                <a class="collapse-item" asp-controller="User" asp-action="Update">Update</a>
                <a class="collapse-item" asp-controller="User" asp-action="Delete">Delete</a>
*@                <a class="collapse-item" asp-controller="Role" asp-action="Index">List</a>
            </div>
        </div>
    </li>

    @*
    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>
    *@

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>